restapi/client: don't use DRF parser for parsing
The DRF parser expect a file-like object containing bytes while
we are passing it a unicode string. The outcome of this is
slumber serialization not working and returning plain bytes
instead of unserialized data.
The fix is trivial and it's just using slumber code for
parsing instead of providing our own.

For reference after making slumber dump exceptions instead of
swallowing here's the root cause:
Traceback (most recent call last): [celery.redirected:235]
File "/venv/lib/python3.5/site-packages/slumber/__init__.py", line 134, in _try_to_serialize_response
  return stype.loads(resp.content.decode(encoding)) [celery.redirected:235]
File "/home/readthedocs/restapi/client.py", line 28, in loads
  return JSONParser().parse(data) [celery.redirected:235]
File "/venv/lib/python3.5/site-packages/rest_framework/parsers.py", line 66, in parse
  return json.load(decoded_stream) [celery.redirected:235]
File "/usr/lib/python3.5/json/__init__.py", line 265, in load
  return loads(fp.read(), [celery.redirected:235]
File "/usr/lib/python3.5/codecs.py", line 493, in read
  newdata = self.stream.read() [celery.redirected:235]
AttributeError: 'str' object has no attribute 'read' [celery.redirected:235]

Fix #4157