GitHub Action: remove `team-reviewers` because it requires a GH-PAT
It has been failing with

```
  Error: Unable to request reviewers. If requesting team reviewers a 'repo' scoped PAT is required.
  Error: Validation Failed: "Could not resolve to a node with the global id of 'T_kwDOAAWW-c4ATMYo'."
```

I'm removing it as `team-reviewers` it's not super important here. I'm getting
this notification anyways and reviewing it.