Features: fix `FEATURES` object
```
In [3]: dict(Feature.FEATURES)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[3], line 1
----> 1 dict(Feature.FEATURES)

ValueError: dictionary update sequence element #2 has length 4; 2 is required
```

The object got malformed in
https://github.com/readthedocs/readthedocs.org/pull/12327