Upgrade `postgres-client` to v12 in Docker image
This is required to have a fully compatible client with the new features from
v12, which is the one that we are using on our docker setup, but also in
production.

As a example, the following command fails with the old client:

psql (10.15 (Ubuntu 10.15-0ubuntu0.18.04.1), server 12.5 (Debian 12.5-1.pgdg100+1))
WARNING: psql major version 10, server major version 12.
         Some psql features might not work.
Type "help" for help.

docs_db=# \d oauth_remoterepository
ERROR:  column c.relhasoids does not exist
LINE 1: ...riggers, c.relrowsecurity, c.relforcerowsecurity, c.relhasoi...

(note the differences between client and server versions)

We will need to update this also in our production images.